"""Chat Agent — universal response layer.

ALL user-facing responses pass through this agent, whether from:
  - Simple queries (direct answers)
  - Complex queries (formatted results from planner → supervisor → coding)

Exports standalone node functions — not a sub-graph.
These are used directly in the main workflow.
"""

from __future__ import annotations

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from src.llms import llm_factory
from src.states.main_state import MainState
from src.prompts import load_prompt
from src.config.logger import get_logger

logger = get_logger("agents.chat_agent")


# ── Node functions ───────────────────────────────────────────────────

def simple_response_node(state: MainState) -> dict:
    """Handle simple queries — the response was already generated by input_node."""
    logger.info("Chat agent: delivering simple response")
    return {"final_response": state.get("final_response", "")}


def complex_response_node(state: MainState) -> dict:
    """Format complex task results into a polished user-facing response.

    Instead of relying on the (potentially truncated) message history,
    we build context from completed_tasks which has the actual results.
    """
    system_prompt = load_prompt("chat_agent")

    llm = llm_factory.create("GEMINI_FLASH", temperature=0, max_output_tokens=1024 * 4)

    # Build context from completed tasks — this is reliable and not truncated
    user_query = state.get("user_query", "")
    completed_tasks = state.get("completed_tasks", [])

    task_results = []
    for task in completed_tasks:
        task_results.append(
            f"### Task: {task.get('task_description', 'Unknown')}\n"
            f"**Status**: {task.get('status', 'unknown')}\n"
            f"**Result**: {task.get('result', 'No result')}\n"
        )

    context = "\n---\n".join(task_results) if task_results else "No task results available."

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=f"User's original request: {user_query}"),
        AIMessage(content=f"Here are the results from the agent team:\n\n{context}"),
        HumanMessage(content="Please format a clear, helpful response for the user based on these results."),
    ]

    result = llm.invoke(messages)

    logger.info("Chat agent: formatted complex response (%d chars)", len(result.content))

    return {
        "messages": [result],
        "final_response": result.content,
    }
